import type { Metadata } from "next";
import { aeonik } from "@/fonts/fonts";
import "./globals.css";
import NavBar from "@/reuseable/navBar";
import SmoothScroller from "@/reuseable/SmoothScroller";
import Footer from "@/reuseable/Footer";
import Loader from "@/reuseable/loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${aeonik.variable} ${aeonik.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative bg-black text-white font-sans">
        <Loader />
        <SmoothScroller>
          <NavBar className="absolute top-0 left-0 right-0" />
          {children}
        </SmoothScroller>
        <Footer />
      </body>
    </html>
  );
}
